import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, existsSync, readdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import * as O from '../systems/overrides.mjs';
import * as E from '../admin/overrides.mjs';
import * as Http from '../admin/conteudo-http.mjs';
import * as A from '../admin/acesso.mjs';
import { CATALOGO, ITEM_CATALOG } from '../systems/dados.mjs';

const pasta = mkdtempSync(join(tmpdir(), 'ov-'));
E.CAMINHOS.arquivo = join(pasta, 'monstros.json');
E.CAMINHOS.versoes = join(pasta, '_versoes', 'monstros');
after(() => rmSync(pasta, { recursive: true, force: true }));
const limpa = () => { rmSync(pasta, { recursive: true, force: true }); };
const arquivo = () => JSON.parse(readFileSync(E.CAMINHOS.arquivo, 'utf8'));
const REAL = JSON.parse(readFileSync(new URL('../gamedata/catalog-real.json', import.meta.url), 'utf8')).bestiary;
const ctx = { ...O.contextoDoJogo(ITEM_CATALOG) };
const val = (key, ov, extra = {}) => O.validarMonstro(key, ov, { ...ctx, original: REAL[key] ?? null, existeMonstro: (k) => !!REAL[k], ...extra });

test('OV1. validação: só campos com suporte real; números, elementos, loot (item e chance), ataques e sprite conferem com o jogo', () => {
  assert.deepEqual(val('troll', { hp: 80, exp: 25, armor: 8, speed: 70, name: 'Troll', elements: { fire: 50 }, loot: [{ id: 3031, chance: 1 }], ataques: [{ tipo: 'melee', min: 0, max: 20, intervalo: 2000, chance: 100 }] }).erros, []);
  const erros = (ov) => val('troll', ov).erros.join(' | ');
  assert.match(erros({ voo: true }), /campo "voo" não tem suporte/);
  assert.match(erros({ hp: 0 }), /vida/);
  assert.match(erros({ hp: 1.5 }), /vida/);
  assert.match(erros({ exp: -1 }), /experiência/);
  assert.match(erros({ stars: 9 }), /estrelas/);
  assert.match(erros({ name: '' }), /nome/);
  assert.match(erros({ elements: { raio: 10 } }), /elemento "raio" desconhecido/);
  assert.match(erros({ elements: { fire: 5000 } }), /entre -1000 e 1000/);
  assert.match(erros({ loot: [{ id: 99999999, chance: 0.5 }] }), /não existe no catálogo/);
  assert.match(erros({ loot: [{ id: 3031, chance: 5 }] }), /fração/);
  assert.match(erros({ look: 99999 }), /sprite/);
  assert.match(erros({ ataques: [{ tipo: 'melee', min: 30, max: 10, intervalo: 2000, chance: 100 }] }), /mínimo \(30\) é maior/);
  assert.match(erros({ ataques: [{ tipo: 'magia', min: 1, max: 2, intervalo: 2000, chance: 100 }] }), /precisa de um elemento/);
  assert.match(erros({ ataques: [{ tipo: 'melee', min: 1, max: 2, intervalo: 10, chance: 100, hack: 1 }] }), /"hack" não tem suporte|intervalo/);
  assert.match(val('nao-existe', { hp: 5 }).erros.join(), /não existe no bestiário/);
  assert.match(val('novo-bicho', { base: 'inexistente' }, { original: null }).erros.join(), /base "inexistente" não existe/);
  assert.match(val('troll', { base: 'troll' }).erros.join(), /já existe um monstro com essa chave/);
  assert.ok(val('troll-x', { base: 'troll', loot: [{ id: 3031, chance: 0.1 }, { id: 3031, chance: 0.2 }] }, { original: null }).avisos.some((a) => /mais de uma vez/.test(a)));
});

test('OV2. aplicar: o efetivo = original + diferenças (loot e ataques substituem; resistências juntam); o original não é alterado', () => {
  const troll = structuredClone(REAL.troll);
  const novo = O.aplicarNoMonstro(troll, { hp: 99, elements: { fire: 50 }, loot: [{ id: 3031, chance: 1 }], look: 15, colors: { head: 5 } });
  assert.equal(novo.hp, 99);
  assert.deepEqual(novo.elements, { ...troll.elements, fire: 50 });
  assert.deepEqual(novo.loot.map((l) => l.id), [3031]);
  assert.equal(novo.colors.head, 5);
  assert.equal(troll.hp, REAL.troll.hp, 'o original não muda');
  const b = { troll: structuredClone(REAL.troll), rotworm: structuredClone(REAL.rotworm) };
  const r = O.aplicarNoBestiario(b, { ativo: true, monstros: { troll: { hp: 70 }, 'troll-guerreiro': { base: 'troll', name: 'Troll Guerreiro', hp: 200 }, rotworm: { hp: -5 }, fantasma: { hp: 5 }, desligado: { ativo: false, hp: 1 } } }, ctx, () => {});
  assert.deepEqual([r.aplicados, r.criados], [['troll'], ['troll-guerreiro']]);
  assert.deepEqual(r.ignorados.map((i) => i.key).sort(), ['fantasma', 'rotworm']);
  assert.equal(b.troll.hp, 70);
  assert.equal(b['troll-guerreiro'].hp, 200);
  assert.equal(b['troll-guerreiro'].name, 'Troll Guerreiro');
  assert.equal(b['troll-guerreiro'].armor, REAL.troll.armor, 'a variação herda o resto do original');
  assert.equal(b.rotworm.hp, REAL.rotworm.hp, 'override inválido não altera nada');
  assert.equal(O.aplicarNoBestiario(b, { ativo: false, monstros: { troll: { hp: 1 } } }, ctx).aplicados.length, 0, 'camada desligada: nada se aplica');
  const poderes = { troll: { ataques: [{ tipo: 'melee', min: 0, max: 15, intervalo: 2000, chance: 100 }], curas: [] } };
  O.aplicarNosPoderes(poderes, { ativo: true, monstros: { troll: { ataques: [{ tipo: 'melee', min: 5, max: 9, intervalo: 1000, chance: 100 }] }, 'troll-guerreiro': { base: 'troll' } } });
  assert.equal(poderes.troll.ataques[0].max, 9);
  assert.equal(poderes['troll-guerreiro'].ataques[0].max, 15, 'a variação herdou os poderes ORIGINAIS da base (a alteração do troll não vaza)');
});

test('OV3. propor (sem gravar): original × efetivo com variação %, impacto no dano por segundo e no valor do loot, avisos de balanceamento e de uso', () => {
  limpa();
  const p = E.propor('troll', { hp: 100, exp: 20, ataques: [{ tipo: 'melee', min: 0, max: 60, intervalo: 2000, chance: 100 }], loot: [{ id: 3031, chance: 1 }] });
  assert.equal(p.ok, true);
  const hp = p.mudancas.find((m) => m.campo === 'hp');
  assert.deepEqual([hp.antes, hp.depois, hp.variacaoPct], [REAL.troll.hp, 100, 100]);
  assert.ok(!p.mudancas.some((m) => m.campo === 'exp'), 'valor igual ao original não é mudança');
  const dano = p.mudancas.find((m) => m.campo === 'ataques').danoPorSegundo;
  assert.equal(dano.antes, 4, '(0+15)/2 × 100% ÷ 2 s');
  assert.equal(dano.depois, 15, '(0+60)/2 ÷ 2 s');
  assert.ok(p.mudancas.find((m) => m.campo === 'loot').valorEsperado.depois >= 0);
  assert.ok(p.avisos.some((a) => /BALANCEAMENTO — hp: \+100%/.test(a)));
  assert.ok(p.avisos.some((a) => /BALANCEAMENTO — dano por segundo: \+300%/.test(a)));
  assert.ok(p.avisos.some((a) => /USO — Troll aparece em \d+ lugar/.test(a)), 'diz onde o troll é usado');
  assert.equal(p.usos >= 1, true);
  assert.equal(E.propor('troll', null).semMudancas, true);
  assert.equal(existsSync(E.CAMINHOS.arquivo), false, 'propor não grava');
  assert.equal(E.propor('troll', { hp: -1 }).ok, false);
});

test('OV4. salvar grava SÓ a diferença (o original e o resto do arquivo intactos), guarda versão, recusa erro sem gravar; reverter apaga a entrada', () => {
  limpa();
  const r = E.salvar('troll', { hp: 90, elements: { fire: 40 } });
  assert.equal(r.ok, true);
  assert.match(r.comoPublicar, /commit e publique pelo deploy/);
  assert.deepEqual(arquivo().monstros, { troll: { hp: 90, elements: { fire: 40 } } });
  assert.equal(arquivo().ativo, true);
  assert.equal(existsSync(E.CAMINHOS.versoes), false, 'a primeira gravação não tem versão anterior');
  E.salvar('rotworm', { exp: 99 });
  assert.equal(readdirSync(E.CAMINHOS.versoes).length, 1);
  assert.deepEqual(JSON.parse(readFileSync(join(E.CAMINHOS.versoes, '1.json'), 'utf8')).monstros, { troll: { hp: 90, elements: { fire: 40 } } }, 'a versão guardada é a de antes');
  const antes = readFileSync(E.CAMINHOS.arquivo, 'utf8');
  assert.equal(E.salvar('troll', { hp: -3 }).ok, false);
  assert.equal(readFileSync(E.CAMINHOS.arquivo, 'utf8'), antes, 'erro não grava');
  assert.equal(E.reverter('troll').ok, true);
  assert.deepEqual(Object.keys(arquivo().monstros), ['rotworm']);
  assert.equal(E.reverter('troll').ok, false);
  assert.equal(E.obter('troll').efetivo.hp, REAL.troll.hp, 'depois de reverter o efetivo é o original');
  assert.equal(JSON.parse(readFileSync(new URL('../gamedata/catalog-real.json', import.meta.url), 'utf8')).bestiary.troll.hp, REAL.troll.hp, 'o catálogo importado nunca é tocado');
});

test('OV5. duplicar cria uma VARIAÇÃO (original intacto); chave repetida é recusada; variação em uso não se apaga; desligar a camada/uma entrada não apaga nada', () => {
  limpa();
  const d = E.duplicar('troll', 'troll-guerreiro', 'Troll Guerreiro');
  assert.equal(d.ok, true);
  assert.deepEqual(arquivo().monstros['troll-guerreiro'], { base: 'troll', name: 'Troll Guerreiro' });
  assert.equal(E.duplicar('troll', 'troll-guerreiro').ok, false);
  assert.equal(E.duplicar('troll', 'troll').ok, false, 'já existe no bestiário');
  assert.equal(E.duplicar('inexistente', 'x-y').ok, false);
  const ficha = E.obter('troll-guerreiro');
  assert.equal(ficha.ehVariacao, true);
  assert.equal(ficha.efetivo.name, 'Troll Guerreiro');
  assert.equal(ficha.efetivo.hp, REAL.troll.hp);
  assert.equal(E.salvar('troll-guerreiro', { base: 'troll', name: 'Troll Guerreiro', hp: 150 }).ok, true);
  assert.equal(E.obter('troll-guerreiro').efetivo.hp, 150);
  assert.equal(E.definirAtivo(false, 'troll-guerreiro').ok, true);
  assert.deepEqual(arquivo().monstros['troll-guerreiro'].ativo, false);
  assert.equal(E.definirAtivo(true, 'troll-guerreiro').ok, true);
  assert.equal(E.definirAtivo(false).ok, true);
  assert.equal(arquivo().ativo, false);
  assert.equal(Object.keys(arquivo().monstros).length, 1, 'desligar não apaga');
  assert.equal(E.definirAtivo('sim').ok, false);
  assert.equal(E.listar({ filtro: 'com-override' }).itens.map((i) => i.key).includes('troll-guerreiro'), true);
  assert.equal(E.reverter('troll-guerreiro').ok, true, 'variação sem uso pode ser apagada');
});

test('OV6. restaurar volta uma versão anterior do arquivo (guardando a atual); versão inexistente é recusada', () => {
  limpa();
  E.salvar('troll', { hp: 60 });
  E.salvar('troll', { hp: 70 });
  E.salvar('troll', { hp: 80 });
  assert.deepEqual(E.versoes(), [2, 1]);
  assert.equal(E.restaurar(1).ok, true);
  assert.equal(arquivo().monstros.troll.hp, 60);
  assert.equal(E.restaurar(99).ok, false);
});

test('OV7. O JOGO APLICA o que foi salvo: um processo novo (apontado para os overrides) enxerga o monstro alterado, a variação, os ataques novos e ignora o inválido — sem tocar no original', () => {
  limpa();
  E.salvar('troll', { hp: 777, exp: 55, elements: { fire: 60 }, ataques: [{ tipo: 'melee', min: 3, max: 33, intervalo: 1500, chance: 100 }] });
  E.duplicar('troll', 'troll-guerreiro', 'Troll Guerreiro');
  const dados = arquivo();
  dados.monstros.rotworm = { hp: -1 };
  dados.monstros['inexistente-xx'] = { hp: 5 };
  writeFileSync(E.CAMINHOS.arquivo, JSON.stringify(dados));
  const codigo = `const D = await import(${JSON.stringify(new URL('../systems/dados.mjs', import.meta.url).href)});
    const P = await import(${JSON.stringify(new URL('../systems/poderes.mjs', import.meta.url).href)});
    const M = await import(${JSON.stringify(new URL('../systems/hunt/monstros.mjs', import.meta.url).href)});
    const b = D.CATALOGO.bestiary; const m = M.criarMonstro({ key: 'troll', x: 1, y: 1 }, null);
    console.log(JSON.stringify({ hp: b.troll.hp, exp: b.troll.exp, fogo: b.troll.elements.fire, rotworm: b.rotworm.hp, variacao: b['troll-guerreiro']?.name, varHp: b['troll-guerreiro']?.hp, fantasma: !!b['inexistente-xx'], noJogo: m.maxHp, ataque: P.temPoderes({ key: 'troll' }), aplicados: D.resultadoDosOverrides.aplicados, ignorados: D.resultadoDosOverrides.ignorados.map((i) => i.key).sort() }));`;
  const saida = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '-e', codigo], { env: { ...process.env, DRAEVOR_OVERRIDES: pasta }, encoding: 'utf8' }).trim().split('\n').at(-1));
  assert.equal(saida.hp, 777);
  assert.equal(saida.noJogo, 777, 'o bicho que o jogo cria na hunt já nasce com a vida nova');
  assert.equal(saida.exp, 55);
  assert.equal(saida.fogo, 60);
  assert.equal(saida.variacao, 'Troll Guerreiro');
  assert.equal(saida.varHp, 777, 'duplicar um monstro já alterado leva as alterações dele para a variação');
  assert.equal(saida.rotworm, REAL.rotworm.hp, 'override inválido ignorado');
  assert.equal(saida.fantasma, false);
  assert.deepEqual(saida.ignorados, ['inexistente-xx', 'rotworm']);
  assert.deepEqual(saida.aplicados, ['troll']);
  assert.equal(CATALOGO.bestiary.troll.hp, REAL.troll.hp, 'o jogo DESTE processo não mudou (só vale no boot): salvar não é publicar');
  const sem = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '-e', `const D = await import(${JSON.stringify(new URL('../systems/dados.mjs', import.meta.url).href)}); console.log(JSON.stringify({ hp: D.CATALOGO.bestiary.troll.hp }))`], { env: { ...process.env, DRAEVOR_OVERRIDES: join(pasta, 'nao-existe') }, encoding: 'utf8' }).trim().split('\n').at(-1));
  assert.equal(sem.hp, REAL.troll.hp, 'sem arquivo de overrides o jogo é o original');
});

test('OV8. rotas: leitura, pré-visualização (não grava) e ações (gravam); o acesso classifica certo; a tela só usa o servidor', async () => {
  limpa();
  const chama = async (metodo, rota, corpo = {}, query = '') => { const r = []; await Http.atender({ method: metodo }, {}, `/api/mapas/_conteudo/${rota}`, new URL(`http://x/?${query}`), { json: (a, c, b) => r.push([c, b]), corpoJson: async () => corpo }); return r[0]; };
  assert.ok((await chama('GET', 'overrides/monstros', {}, 'q=troll'))[1].total >= 1);
  assert.equal((await chama('GET', 'overrides/monstros/troll'))[1].key, 'troll');
  assert.equal((await chama('GET', 'overrides/monstros/nao-existe'))[0], 404);
  const v = (await chama('POST', 'overrides/validar', { key: 'troll', override: { hp: 100 } }))[1];
  assert.equal(v.ok, true);
  assert.equal(existsSync(E.CAMINHOS.arquivo), false);
  assert.equal((await chama('POST', 'overrides', { acao: 'salvar', key: 'troll', override: { hp: 100 } }))[1].ok, true);
  assert.equal((await chama('POST', 'overrides', { acao: 'duplicar', key: 'troll', novaKey: 'troll-x' }))[1].ok, true);
  assert.equal((await chama('POST', 'overrides', { acao: 'ativo', ativo: false }))[1].ok, true);
  assert.equal((await chama('POST', 'overrides', { acao: 'xyz' }))[0], 400);
  assert.equal((await chama('GET', 'overrides/versoes'))[1].versoes.length >= 1, true);
  assert.equal(A.classeDaRota('POST', '/api/mapas/_conteudo/overrides/validar'), 'leitura');
  assert.equal(A.classeDaRota('POST', '/api/mapas/_conteudo/overrides'), 'grava', 'em produção a gravação é recusada');
  assert.equal(A.classeDaRota('GET', '/api/mapas/_conteudo/overrides/monstros/troll'), 'leitura');
});

test('OV9. a tela: o override em edição fica MÍNIMO (valor igual ao original sai), reconhece alteração real e a ligação com Mobs/Biblioteca/menu existe', async () => {
  const { definirCampo, valorEfetivo, resistenciasEfetivas, alterado, paraEnviar } = await import('../frontend/client/src/editor-mobs.mjs');
  const orig = { name: 'Troll', hp: 50, exp: 20, elements: { fire: 0, energy: 20, earth: -10 }, look: 15 };
  const ov = {};
  definirCampo(orig, ov, 'hp', 80);
  assert.deepEqual(ov, { hp: 80 });
  definirCampo(orig, ov, 'hp', 50);
  assert.deepEqual(ov, {}, 'voltar ao valor original remove o campo do override');
  definirCampo(orig, ov, 'name', '');
  assert.deepEqual(ov, {}, 'vazio não vira override');
  definirCampo(orig, ov, 'elements', { fire: 50, energy: 20, earth: -10 });
  assert.deepEqual(ov.elements, { fire: 50 }, 'só a resistência que difere do original entra');
  assert.deepEqual(resistenciasEfetivas(orig, ov), { fire: 50, energy: 20, earth: -10 });
  definirCampo(orig, ov, 'elements', { fire: 0, energy: 20, earth: -10 });
  assert.equal(ov.elements, undefined);
  ov.exp = 30;
  assert.equal(valorEfetivo(orig, ov, 'exp'), 30);
  assert.equal(valorEfetivo(orig, ov, 'hp'), 50);
  assert.equal(alterado({ hp: 80 }, { hp: 80 }), false);
  assert.equal(alterado({ hp: 90 }, { hp: 80 }), true);
  assert.equal(alterado({ hp: 80, ativo: false }, { hp: 80 }), false, 'ligar/desligar não conta como edição');
  assert.equal(alterado({ base: 'troll', name: 'X' }, { base: 'troll', name: 'X' }), false, 'variação recém-aberta não está suja');
  assert.equal(paraEnviar({}), null);
  assert.equal(paraEnviar({ ativo: false }), null);
  assert.deepEqual(paraEnviar({ hp: 1 }), { hp: 1 });
  const conteudo = readFileSync(new URL('../frontend/client/src/editor-conteudo.mjs', import.meta.url), 'utf8');
  assert.match(conteudo, /criarEditorDeMobs/);
  assert.match(conteudo, /Editar mobs \(overrides\)/);
  assert.match(conteudo, /modo: 'parcial', dica: 'consulta e edição por override/);
  assert.match(readFileSync(new URL('../frontend/client/src/editor-biblioteca.mjs', import.meta.url), 'utf8'), /acaoDaFicha/);
  const tela = readFileSync(new URL('../frontend/client/src/editor-mobs.mjs', import.meta.url), 'utf8');
  for (const r of ["'overrides/validar'", "'overrides'", 'overrides/monstros']) assert.ok(tela.includes(r), r);
  assert.match(tela, /confirmar\(/);
  assert.match(tela, /original: \$\{texto\}/, 'o original aparece ao lado de cada campo');
});
